networks:
  taskflow-network:
    driver: bridge

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env
    depends_on:
      - mysql
    networks:
      - taskflow-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - taskflow-network

  mysql:
    image: mysql:8
    container_name: mysql-taskflow
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: taskflow
      MYSQL_ROOT_HOST: "%"  # ?? Permite conexiones remotas
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - taskflow-network

volumes:
  mysql_data:
